/**
 * Generates `apps/web/src/lib/language-logos.ts` from simple-icons.
 *
 * The package ships its icons as raw SVG files plus a five-megabyte JavaScript
 * index. Importing that index would make every dev start and every build parse
 * it, so the seven paths this product actually uses are extracted here instead.
 *
 * The result is committed, so the app builds without simple-icons installed.
 * Re-run with `npm run sync:icons` to pick up upstream logo changes.
 *
 * simple-icons artwork is CC0 1.0; each logo remains a trademark of its owner
 * and is used here only to identify the file type.
 */

import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const SOURCE = path.join(ROOT, 'node_modules/simple-icons/icons');
const TARGET = path.join(ROOT, 'apps/web/src/lib/language-logos.ts');

/** Key in the generated map -> file in simple-icons. */
const WANTED = {
  react: 'react',
  next: 'nextdotjs',
  tailwind: 'tailwindcss',
  typescript: 'typescript',
  javascript: 'javascript',
  css: 'css',
  html: 'html5',
  json: 'json',
  markdown: 'markdown',

  // Languages the repository browser meets on GitHub but the editor never
  // compiles. They identify a repository; they are not file-type icons.
  astro: 'astro',
  sql: 'postgresql',
  python: 'python',
  go: 'go',
  rust: 'rust',
  java: 'openjdk',
  php: 'php',
  ruby: 'ruby',
  shell: 'gnubash',
  vue: 'vuedotjs',
  svelte: 'svelte',
  docker: 'docker',
};

if (!fs.existsSync(SOURCE)) {
  console.error('simple-icons is not installed. Run `npm install` first.');
  process.exit(1);
}

const entries = [];

for (const [key, file] of Object.entries(WANTED)) {
  const svgPath = path.join(SOURCE, `${file}.svg`);
  if (!fs.existsSync(svgPath)) throw new Error(`simple-icons has no ${file}.svg`);

  const svg = fs.readFileSync(svgPath, 'utf8');

  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  if (viewBox !== '0 0 24 24') throw new Error(`${file}.svg uses an unexpected viewBox`);

  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((match) => match[1]);
  if (paths.length !== 1) throw new Error(`${file}.svg has ${paths.length} paths, expected one`);

  const title = svg.match(/<title>([^<]+)<\/title>/)?.[1] ?? file;

  entries.push({ key, title, d: paths[0] });
}

const body = entries
  .map(({ key, title, d }) => `  /** ${title} */\n  ${key}: '${d.replace(/'/g, "\\'")}',`)
  .join('\n');

const version = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'node_modules/simple-icons/package.json'), 'utf8'),
).version;

fs.writeFileSync(
  TARGET,
  `/*
 * Generated by scripts/sync-icons.mjs from simple-icons ${version}. Do not edit.
 *
 * Official language marks, drawn on a 24x24 grid. The artwork is CC0 1.0; each
 * logo remains a trademark of its owner and is used only to identify a file
 * type. Colour comes from the theme rather than from the brand palette, because
 * several brand colours are unreadable on a light background.
 */

export const LANGUAGE_LOGOS = {
${body}
} as const;

export type LanguageLogo = keyof typeof LANGUAGE_LOGOS;
`,
);

console.log(`Wrote ${path.relative(ROOT, TARGET).replace(/\\/g, '/')}`);
for (const { key, title, d } of entries) {
  console.log(`  ${key.padEnd(11)} ${title.padEnd(12)} ${d.length} chars`);
}
